version: "3.3"

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src"
      - "/usr/src/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
