# build environment
FROM node:13.12.0-alpine as build
WORKDIR /usr/src
ENV PATH /usr/src/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN apk add --update python make g++\
    && rm -rf /var/cache/apk/*
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
